#!/usr/bin/env node
//
// Writes src/_version.ts from package.json#version so the bundled
// `VERSION` export (and the internal User-Agent constant) stay in
// lockstep with the published package.
//
// Runs as `prebuild` — before tsup. During the release workflow
// (.github/workflows/release.yml), `npm version --no-git-tag-version`
// already updated package.json from the git tag, so this picks up the
// real release version. In local dev it just mirrors whatever
// package.json currently says.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");

const pkg = JSON.parse(readFileSync(join(repoRoot, "package.json"), "utf-8"));
const version = pkg.version;

if (!version || typeof version !== "string") {
  console.error("sync-version: package.json has no string `version` field");
  process.exit(1);
}

const out = `// Auto-generated by scripts/sync-version.mjs. Do not edit by hand.
// Mirrors package.json#version at build time so the bundled VERSION
// export matches the published npm package.
export const VERSION = "${version}";
`;

const target = join(repoRoot, "src", "_version.ts");
writeFileSync(target, out, "utf-8");
console.log(`sync-version: wrote src/_version.ts (VERSION="${version}")`);
